version: '3.8'

services:
  app:
    build: .
    ports:
      - '3030:3030'
    environment:
      MONGODB_URI: mongodb://mongo:27017/koi-core-api
      JWT_SECRET: your_jwt_secret
      GOOGLE_CLIENT_ID: your_google_client_id
      GOOGLE_CLIENT_SECRET: your_google_client_secret
      POSTMARK_API_KEY: your_postmark_api_key
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
